name: commit-push-if-changed
description: Commit and Push if changed

inputs:
  message-for-no-changes:
    description: Message for no changes
    required: false
    default: No changes to commit
  commit-user-name:
    description: Commit user name
    required: false
    default: github-actions[bot]
  commit-user-email:
    description: Commit user email
    required: false
    default: github-actions[bot]@users.noreply.github.com
  commit-message:
    description: Commit message
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Check for changes
      shell: bash
      run: |
        if git diff --exit-code; then
          echo "${{ inputs.message-for-no-changes }}"
        else
          git config user.email '${{ inputs.commit-user-email }}'
          git config user.name '${{ inputs.commit-user-name }}'
          git add .
          git commit -m '${{ inputs.commit-message }}'
          git push
        fi
