name: Auto-Generate

on:
  - push

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up terraform
        # actions/setup-terraform@v3.1.2 at 2025-05-09
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
      - name: Checkout code
        # actions/checkout@v4.2.2 at 2025-05-09
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up terraform-docs
        uses: ./.github/actions/setup-terraform-docs
        with:
          release: v0.20.0
          release-commit: cf462c5da36feb66051cf0a6f1124594ed9adc7c
      - name: format
        run: terraform fmt -recursive
      - name: commit for format
        uses: ./.github/actions/commit-push-if-changed
        with:
          message-for-no-changes: No changes to commit
          commit-user-name: github-actions[bot]
          commit-user-email: github-actions[bot]@users.noreply.github.com
          commit-message: apply terraform fmt
      - name: generate API.md
        run: |
          find . -name '*.tf' -not -path '*/.terraform/*' \
            | xargs dirname \
            | sort -u \
            | while read path_module
              do
                terraform-docs markdown table --output-file API.md --output-mode replace "${path_module}"
              done
      - name: commit for generated docs
        uses: ./.github/actions/commit-push-if-changed
        with:
          message-for-no-changes: No changes to commit
          commit-user-name: github-actions[bot]
          commit-user-email: github-actions[bot]@users.noreply.github.com
          commit-message: terraform-docs document updated
